import {
  faInstagram, faFacebook, faXTwitter, faThreads, faYoutube, faTiktok,
  faWhatsapp, faTelegram, faSnapchat, faPinterest, faLinkedin, faReddit,
  faDiscord, faTwitch, faMastodon, faLine, faSkype, faSpotify,
  faAmazon, faAmazonPay, faPaypal, faStripe, faCcStripe, faApplePay,
  faGooglePay, faBitcoin, faEthereum, faCcVisa, faCcMastercard, faCcAmex,
  faCcPaypal, faCcAmazonPay, faGoogle, faGoogleDrive, faGooglePlay,
  faApple, faAppStoreIos, faMicrosoft, faAndroid, faWindows, faChrome,
  faFirefox, faSafari, faEdge, faGithub, faGitlab, faShopify, faWordpress,
  faFigma, faSlack, faZoom, faDropbox, faTrello, faJira, faLinux, faUbuntu,
  faSteam, faPlaystation, faXbox, faUber, faAirbnb, faEbay, faAlipay, faEtsy,
  faVimeoV, faSoundcloud, faDeezer, faWaze, faYelp, faTumblr, faMedium,
  faPatreon, faKickstarter, faProductHunt,
} from '@fortawesome/free-brands-svg-icons';
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';

export type BrandIconEntry =
  | { iconType: 'fa'; key: string; label: string; icon: IconDefinition; category: string }
  | { iconType: 'lucide'; key: string; label: string; lucideName: string; category: string };

export const BRAND_ICONS: BrandIconEntry[] = [
  { iconType: 'fa', key: 'instagram', label: 'Instagram', icon: faInstagram, category: 'Sosial' },
  { iconType: 'fa', key: 'facebook', label: 'Facebook', icon: faFacebook, category: 'Sosial' },
  { iconType: 'fa', key: 'x-twitter', label: 'X / Twitter', icon: faXTwitter, category: 'Sosial' },
  { iconType: 'fa', key: 'threads', label: 'Threads', icon: faThreads, category: 'Sosial' },
  { iconType: 'fa', key: 'youtube', label: 'YouTube', icon: faYoutube, category: 'Sosial' },
  { iconType: 'fa', key: 'tiktok', label: 'TikTok', icon: faTiktok, category: 'Sosial' },
  { iconType: 'fa', key: 'whatsapp', label: 'WhatsApp', icon: faWhatsapp, category: 'Sosial' },
  { iconType: 'fa', key: 'telegram', label: 'Telegram', icon: faTelegram, category: 'Sosial' },
  { iconType: 'fa', key: 'line', label: 'LINE', icon: faLine, category: 'Sosial' },
  { iconType: 'fa', key: 'snapchat', label: 'Snapchat', icon: faSnapchat, category: 'Sosial' },
  { iconType: 'fa', key: 'pinterest', label: 'Pinterest', icon: faPinterest, category: 'Sosial' },
  { iconType: 'fa', key: 'linkedin', label: 'LinkedIn', icon: faLinkedin, category: 'Sosial' },
  { iconType: 'fa', key: 'reddit', label: 'Reddit', icon: faReddit, category: 'Sosial' },
  { iconType: 'fa', key: 'discord', label: 'Discord', icon: faDiscord, category: 'Sosial' },
  { iconType: 'fa', key: 'twitch', label: 'Twitch', icon: faTwitch, category: 'Sosial' },
  { iconType: 'fa', key: 'mastodon', label: 'Mastodon', icon: faMastodon, category: 'Sosial' },
  { iconType: 'fa', key: 'skype', label: 'Skype', icon: faSkype, category: 'Sosial' },
  { iconType: 'fa', key: 'medium', label: 'Medium', icon: faMedium, category: 'Sosial' },
  { iconType: 'fa', key: 'tumblr', label: 'Tumblr', icon: faTumblr, category: 'Sosial' },

  { iconType: 'fa', key: 'spotify', label: 'Spotify', icon: faSpotify, category: 'Streaming' },
  { iconType: 'fa', key: 'amazon', label: 'Amazon', icon: faAmazon, category: 'Streaming' },
  { iconType: 'fa', key: 'vimeo', label: 'Vimeo', icon: faVimeoV, category: 'Streaming' },
  { iconType: 'fa', key: 'soundcloud', label: 'SoundCloud', icon: faSoundcloud, category: 'Streaming' },
  { iconType: 'fa', key: 'deezer', label: 'Deezer', icon: faDeezer, category: 'Streaming' },
  { iconType: 'lucide', key: 'netflix', label: 'Netflix', lucideName: 'Tv', category: 'Streaming' },
  { iconType: 'lucide', key: 'disney-plus', label: 'Disney+', lucideName: 'Star', category: 'Streaming' },
  { iconType: 'lucide', key: 'hbo-max', label: 'HBO Max', lucideName: 'Film', category: 'Streaming' },
  { iconType: 'fa', key: 'apple-tv', label: 'Apple TV', icon: faApple, category: 'Streaming' },
  { iconType: 'lucide', key: 'crunchyroll', label: 'Crunchyroll', lucideName: 'PlayCircle', category: 'Streaming' },
  { iconType: 'lucide', key: 'vidio', label: 'Vidio', lucideName: 'Tv', category: 'Streaming' },

  { iconType: 'fa', key: 'paypal', label: 'PayPal', icon: faPaypal, category: 'Keuangan' },
  { iconType: 'fa', key: 'stripe', label: 'Stripe', icon: faStripe, category: 'Keuangan' },
  { iconType: 'fa', key: 'cc-stripe', label: 'Stripe CC', icon: faCcStripe, category: 'Keuangan' },
  { iconType: 'fa', key: 'apple-pay', label: 'Apple Pay', icon: faApplePay, category: 'Keuangan' },
  { iconType: 'fa', key: 'google-pay', label: 'Google Pay', icon: faGooglePay, category: 'Keuangan' },
  { iconType: 'fa', key: 'amazon-pay', label: 'Amazon Pay', icon: faAmazonPay, category: 'Keuangan' },
  { iconType: 'fa', key: 'cc-amazon-pay', label: 'Amazon Pay CC', icon: faCcAmazonPay, category: 'Keuangan' },
  { iconType: 'fa', key: 'bitcoin', label: 'Bitcoin', icon: faBitcoin, category: 'Keuangan' },
  { iconType: 'fa', key: 'ethereum', label: 'Ethereum', icon: faEthereum, category: 'Keuangan' },
  { iconType: 'fa', key: 'cc-visa', label: 'Visa', icon: faCcVisa, category: 'Keuangan' },
  { iconType: 'fa', key: 'cc-mastercard', label: 'Mastercard', icon: faCcMastercard, category: 'Keuangan' },
  { iconType: 'fa', key: 'cc-amex', label: 'Amex', icon: faCcAmex, category: 'Keuangan' },
  { iconType: 'fa', key: 'cc-paypal', label: 'PayPal CC', icon: faCcPaypal, category: 'Keuangan' },
  { iconType: 'fa', key: 'alipay', label: 'Alipay', icon: faAlipay, category: 'Keuangan' },
  { iconType: 'fa', key: 'ebay', label: 'eBay', icon: faEbay, category: 'Keuangan' },

  { iconType: 'lucide', key: 'ovo', label: 'OVO', lucideName: 'Wallet', category: 'E-Wallet' },
  { iconType: 'lucide', key: 'dana', label: 'DANA', lucideName: 'Smartphone', category: 'E-Wallet' },
  { iconType: 'lucide', key: 'gopay', label: 'GoPay', lucideName: 'Banknote', category: 'E-Wallet' },
  { iconType: 'lucide', key: 'shopee-pay', label: 'ShopeePay', lucideName: 'ShoppingBag', category: 'E-Wallet' },
  { iconType: 'lucide', key: 'link-aja', label: 'LinkAja', lucideName: 'ArrowLeftRight', category: 'E-Wallet' },
  { iconType: 'lucide', key: 'jenius', label: 'Jenius', lucideName: 'CreditCard', category: 'E-Wallet' },
  { iconType: 'lucide', key: 'blu', label: 'Blu by BCA', lucideName: 'BadgeDollarSign', category: 'E-Wallet' },
  { iconType: 'lucide', key: 'flip', label: 'Flip', lucideName: 'ArrowLeftRight', category: 'E-Wallet' },

  { iconType: 'lucide', key: 'tokopedia', label: 'Tokopedia', lucideName: 'Store', category: 'E-Commerce' },
  { iconType: 'lucide', key: 'shopee', label: 'Shopee', lucideName: 'ShoppingCart', category: 'E-Commerce' },
  { iconType: 'lucide', key: 'lazada', label: 'Lazada', lucideName: 'Package', category: 'E-Commerce' },
  { iconType: 'lucide', key: 'blibli', label: 'Blibli', lucideName: 'Globe', category: 'E-Commerce' },
  { iconType: 'lucide', key: 'bukalapak', label: 'Bukalapak', lucideName: 'Tag', category: 'E-Commerce' },
  { iconType: 'lucide', key: 'traveloka', label: 'Traveloka', lucideName: 'Plane', category: 'E-Commerce' },
  { iconType: 'lucide', key: 'tiket-com', label: 'Tiket.com', lucideName: 'Ticket', category: 'E-Commerce' },
  { iconType: 'fa', key: 'etsy', label: 'Etsy', icon: faEtsy, category: 'E-Commerce' },

  { iconType: 'lucide', key: 'grab', label: 'Grab', lucideName: 'Car', category: 'Transport' },
  { iconType: 'lucide', key: 'gojek', label: 'Gojek', lucideName: 'Bike', category: 'Transport' },
  { iconType: 'fa', key: 'uber', label: 'Uber', icon: faUber, category: 'Transport' },
  { iconType: 'lucide', key: 'indrive', label: 'inDrive', lucideName: 'CarFront', category: 'Transport' },
  { iconType: 'fa', key: 'airbnb', label: 'Airbnb', icon: faAirbnb, category: 'Transport' },
  { iconType: 'fa', key: 'waze', label: 'Waze', icon: faWaze, category: 'Transport' },
  { iconType: 'lucide', key: 'grab-food', label: 'GrabFood', lucideName: 'Utensils', category: 'Transport' },
  { iconType: 'lucide', key: 'go-food', label: 'GoFood', lucideName: 'Pizza', category: 'Transport' },

  { iconType: 'fa', key: 'google', label: 'Google', icon: faGoogle, category: 'Teknologi' },
  { iconType: 'fa', key: 'google-drive', label: 'Google Drive', icon: faGoogleDrive, category: 'Teknologi' },
  { iconType: 'fa', key: 'google-play', label: 'Google Play', icon: faGooglePlay, category: 'Teknologi' },
  { iconType: 'fa', key: 'apple', label: 'Apple', icon: faApple, category: 'Teknologi' },
  { iconType: 'fa', key: 'app-store', label: 'App Store', icon: faAppStoreIos, category: 'Teknologi' },
  { iconType: 'fa', key: 'microsoft', label: 'Microsoft', icon: faMicrosoft, category: 'Teknologi' },
  { iconType: 'fa', key: 'android', label: 'Android', icon: faAndroid, category: 'Teknologi' },
  { iconType: 'fa', key: 'windows', label: 'Windows', icon: faWindows, category: 'Teknologi' },
  { iconType: 'fa', key: 'chrome', label: 'Chrome', icon: faChrome, category: 'Teknologi' },
  { iconType: 'fa', key: 'firefox', label: 'Firefox', icon: faFirefox, category: 'Teknologi' },
  { iconType: 'fa', key: 'safari', label: 'Safari', icon: faSafari, category: 'Teknologi' },
  { iconType: 'fa', key: 'edge', label: 'Edge', icon: faEdge, category: 'Teknologi' },
  { iconType: 'fa', key: 'github', label: 'GitHub', icon: faGithub, category: 'Teknologi' },
  { iconType: 'fa', key: 'gitlab', label: 'GitLab', icon: faGitlab, category: 'Teknologi' },
  { iconType: 'fa', key: 'shopify', label: 'Shopify', icon: faShopify, category: 'Teknologi' },
  { iconType: 'fa', key: 'wordpress', label: 'WordPress', icon: faWordpress, category: 'Teknologi' },
  { iconType: 'fa', key: 'figma', label: 'Figma', icon: faFigma, category: 'Teknologi' },
  { iconType: 'fa', key: 'slack', label: 'Slack', icon: faSlack, category: 'Teknologi' },
  { iconType: 'fa', key: 'zoom', label: 'Zoom', icon: faZoom, category: 'Teknologi' },
  { iconType: 'fa', key: 'dropbox', label: 'Dropbox', icon: faDropbox, category: 'Teknologi' },
  { iconType: 'fa', key: 'trello', label: 'Trello', icon: faTrello, category: 'Teknologi' },
  { iconType: 'fa', key: 'jira', label: 'Jira', icon: faJira, category: 'Teknologi' },
  { iconType: 'fa', key: 'linux', label: 'Linux', icon: faLinux, category: 'Teknologi' },
  { iconType: 'fa', key: 'ubuntu', label: 'Ubuntu', icon: faUbuntu, category: 'Teknologi' },
  { iconType: 'fa', key: 'product-hunt', label: 'Product Hunt', icon: faProductHunt, category: 'Teknologi' },
  { iconType: 'fa', key: 'kickstarter', label: 'Kickstarter', icon: faKickstarter, category: 'Teknologi' },
  { iconType: 'fa', key: 'patreon', label: 'Patreon', icon: faPatreon, category: 'Teknologi' },
  { iconType: 'fa', key: 'yelp', label: 'Yelp', icon: faYelp, category: 'Teknologi' },

  { iconType: 'fa', key: 'steam', label: 'Steam', icon: faSteam, category: 'Game' },
  { iconType: 'fa', key: 'playstation', label: 'PlayStation', icon: faPlaystation, category: 'Game' },
  { iconType: 'fa', key: 'xbox', label: 'Xbox', icon: faXbox, category: 'Game' },
];

export const BRAND_CATEGORIES = Array.from(new Set(BRAND_ICONS.map((b) => b.category)));

export function findBrandIcon(key: string): BrandIconEntry | undefined {
  return BRAND_ICONS.find((b) => b.key === key);
}
