import type { LucideIcon } from 'lucide-react-native';
import {
  Banknote, Building2, PiggyBank, Wallet, CreditCard, Bitcoin,
  Landmark, Package, Utensils, Car, ShoppingBag, Zap, Heart, Film,
  BookOpen, Home, Shirt, Sparkles, Gift, MoreHorizontal, Briefcase,
  Laptop, Store, TrendingUp, RotateCcw, Star, CircleDollarSign,
  Coffee, Gamepad2, Dumbbell, Plane, Bus, Bike, Phone, Wifi,
  Music, Camera, Baby, Flower2, Pizza, ShoppingCart, Receipt,
  Stethoscope, GraduationCap, Trophy, DollarSign,
  ArrowLeftRight, BarChart2, Globe, HelpCircle, Tag, Coins,
  Fuel, Train, Scissors, Lightbulb, Wrench, Leaf, Sun, Moon,
} from 'lucide-react-native';

const ICON_MAP: Record<string, LucideIcon> = {
  Banknote,
  Building2,
  PiggyBank,
  Wallet,
  CreditCard,
  Bitcoin,
  Landmark,
  Package,
  Utensils,
  Car,
  ShoppingBag,
  Zap,
  Heart,
  Film,
  BookOpen,
  Home,
  Shirt,
  Sparkles,
  Gift,
  MoreHorizontal,
  Briefcase,
  Laptop,
  Store,
  TrendingUp,
  RotateCcw,
  Star,
  CircleDollarSign,
  Coffee,
  Gamepad2,
  Dumbbell,
  Plane,
  Bus,
  Bike,
  Phone,
  Wifi,
  Music,
  Camera,
  Baby,
  Flower2,
  Pizza,
  ShoppingCart,
  Receipt,
  Stethoscope,
  GraduationCap,
  Trophy,
  DollarSign,
  ArrowLeftRight,
  BarChart2,
  Globe,
  Tag,
  Coins,
  Fuel,
  Train,
  Scissors,
  Lightbulb,
  Wrench,
  Leaf,
  Sun,
  Moon,
};

export const ALL_LUCIDE_ICON_NAMES = Object.keys(ICON_MAP);

export function getLucideIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? HelpCircle;
}
