import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const dbSchema = appSchema({
  version: 2,
  tables: [
    tableSchema({
      name: 'wallets',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'icon', type: 'string' },
        { name: 'color', type: 'string' },
        { name: 'currency', type: 'string' },
        { name: 'initial_balance', type: 'number' },
        { name: 'is_archived', type: 'boolean' },
        { name: 'sort_order', type: 'number', isOptional: true },
        { name: 'wallet_type', type: 'string', isOptional: true },
        { name: 'show_in_dashboard', type: 'boolean', isOptional: true },
        { name: 'include_in_total', type: 'boolean', isOptional: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'transactions',
      columns: [
        { name: 'tx_type', type: 'string' },
        { name: 'amount', type: 'number' },
        { name: 'currency', type: 'string' },
        { name: 'wallet_id', type: 'string', isIndexed: true },
        { name: 'to_wallet_id', type: 'string', isOptional: true },
        { name: 'category_id', type: 'string', isIndexed: true },
        { name: 'date', type: 'number', isIndexed: true },
        { name: 'note', type: 'string', isOptional: true },
        { name: 'attachment_base64', type: 'string', isOptional: true },
        { name: 'linked_person_name', type: 'string', isOptional: true },
        { name: 'linked_person_phone', type: 'string', isOptional: true },
        { name: 'is_split_of', type: 'string', isOptional: true },
        { name: 'tags', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'categories',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'icon', type: 'string' },
        { name: 'color', type: 'string' },
        { name: 'category_type', type: 'string' },
        { name: 'is_default', type: 'boolean' },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'budgets',
      columns: [
        { name: 'category_id', type: 'string', isIndexed: true },
        { name: 'amount', type: 'number' },
        { name: 'currency', type: 'string' },
        { name: 'period', type: 'string' },
        { name: 'month', type: 'number', isOptional: true },
        { name: 'year', type: 'number', isOptional: true },
        { name: 'notify_at', type: 'number' },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'reminders',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'amount', type: 'number', isOptional: true },
        { name: 'currency', type: 'string' },
        { name: 'due_day', type: 'number' },
        { name: 'period', type: 'string' },
        { name: 'category', type: 'string' },
        { name: 'notify_days_before', type: 'number' },
        { name: 'is_active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'recurring_transactions',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'tx_type', type: 'string' },
        { name: 'amount', type: 'number' },
        { name: 'currency', type: 'string' },
        { name: 'category_id', type: 'string' },
        { name: 'wallet_id', type: 'string' },
        { name: 'note', type: 'string' },
        { name: 'frequency', type: 'string' },
        { name: 'next_due_date', type: 'number' },
        { name: 'is_active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'transaction_templates',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'tx_type', type: 'string' },
        { name: 'category_id', type: 'string' },
        { name: 'wallet_id', type: 'string' },
        { name: 'amount', type: 'number' },
        { name: 'note', type: 'string' },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'tags',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'color', type: 'string', isOptional: true },
        { name: 'use_count', type: 'number' },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'price_cache',
      columns: [
        { name: 'symbol', type: 'string', isIndexed: true },
        { name: 'price_idr', type: 'number' },
        { name: 'price_usd', type: 'number', isOptional: true },
        { name: 'change_24h', type: 'number', isOptional: true },
        { name: 'source', type: 'string' },
        { name: 'fetched_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'settings',
      columns: [
        { name: 'key', type: 'string', isIndexed: true },
        { name: 'value', type: 'string' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'usage_patterns',
      columns: [
        { name: 'event_type', type: 'string', isIndexed: true },
        { name: 'payload', type: 'string', isOptional: true },
        { name: 'ts', type: 'number', isIndexed: true },
      ],
    }),
  ],
});
